kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-role
  namespace: hadoop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-role-binding
  namespace: hadoop
subjects:
- kind: ServiceAccount
  name: hadoop-master
  namespace: hadoop
roleRef:
  kind: Role
  name: hadoop-role
  apiGroup: rbac.authorization.k8s.io