apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordcloud.fullname" . }}-hdfs-nn-pvc
  labels:
    name: {{ include "wordcloud.fullname" . }}-hadoop-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi