apiVersion: v2
name: wordcloud
description: This project extract from

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

dependencies:
  - name: zookeeper
    repository: https://charts.bitnami.com/bitnami
    version: 6.3.0
  - name: hdfs
    repository: https://gradiant.github.io/charts
    version: 0.1.10
  - name: hbase
    repository: https://gradiant.github.io/charts
    version: 0.1.6
  - name: hive
    repository: https://gradiant.github.io/charts
    version: 0.1.6
  - name: airflow
    repository: https://airflow-helm.github.io/charts
    version: 7.16.0
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 12.5.0
  - name: spark
    repository: https://charts.bitnami.com/bitnami
    version: 4.4.1
